#########################################################################
# Title:         Saltbox: UnionFS Role                                  #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Variables

- name: Variables Task
  ansible.builtin.import_tasks: "subtasks/variables.yml"

# Stop Docker Containers

- name: Docker Containers Stop Tasks
  ansible.builtin.import_tasks: "subtasks/docker/containers_stop.yml"
  when: (not containers_list is defined)

# Existing Setup

- name: Legacy Task
  ansible.builtin.import_tasks: "subtasks/legacy.yml"

# Mount Mergerfs

- name: MergerFS Tasks
  ansible.builtin.include_tasks: "subtasks/mergerfs.yml"

- name: Mounts block
  when: ('mounts' in ansible_run_tags)
  block:
    - name: Docker Daemon Tasks
      ansible.builtin.import_tasks: "subtasks/docker/daemon.yml"

    # Start Docker Containers

    - name: Docker Containers Start Tasks
      ansible.builtin.import_tasks: "subtasks/docker/containers_start.yml"
      when: (containers_list is defined)

    - name: Docker Containers Start Tasks (no running containers)
      ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/start_saltbox_docker_containers.yml"
      when: (not containers_list is defined) and unionfs_docker_binary.stat.exists and unionfs_docker_service_running
