##########################################################################################
# Title:         Saltbox: Resources | Tasks | Docker | Stop Saltbox Docker Containers    #
# Author(s):     salty                                                                   #
# URL:           https://github.com/saltyorg/Saltbox                                     #
# --                                                                                     #
##########################################################################################
#                   GNU General Public License v3.0                                      #
##########################################################################################
---
- name: Stop Saltbox Docker Containers
  ansible.builtin.uri:
    url: "{{ docker_controller_url }}/stop{{ _query_var if _query_var is defined else '' }}"
    method: POST
  register: stop_docker_controller_job
  ignore_errors: true

- name: Poll for job completion
  ansible.builtin.uri:
    url: "{{ docker_controller_url }}/job_status/{{ stop_docker_controller_job.json.job_id }}"
    method: GET
  register: stop_job_status
  until: stop_job_status.json.status in ['completed', 'failed']
  retries: 120
  delay: 5
  when: stop_docker_controller_job is success

- name: Check job status
  ansible.builtin.debug:
    msg: "Failed stopping Saltbox Docker containers"
  when:
    - stop_docker_controller_job is success
    - stop_job_status.json.status == 'failed'
