#########################################################################
# Title:         Saltbox: UnionFS | Docker | Container Stop Tasks       #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "UnionFS | Docker | Container Stop | Populate Service Facts"
  ansible.builtin.service_facts:

- name: "UnionFS | Docker | Container Stop | Check to see if docker is installed"
  ansible.builtin.stat:
    path: "/usr/bin/docker"
  register: unionfs_docker_binary

- name: "UnionFS | Docker | Container Stop | Get Docker service state"
  ansible.builtin.set_fact:
    unionfs_docker_service_running: "{{ (services['docker.service'] is defined) and (services['docker.service']['state'] == 'running') }}"
    unionfs_docker_controller_service_running: "{{ (services['saltbox_managed_docker_controller.service'] is defined) and (services['saltbox_managed_docker_controller.service']['state'] == 'running') }}"
  when: unionfs_docker_binary.stat.exists

- name: "UnionFS | Docker | Container Stop | Tasks for when Docker exists and is running"
  when: unionfs_docker_binary.stat.exists and unionfs_docker_service_running
  block:
    - name: "UnionFS | Docker | Container Stop | Block Docker Controller"
      ansible.builtin.uri:
        url: "{{ docker_controller_url }}/block/20"
        method: POST
        timeout: 600
      ignore_errors: true
      when: unionfs_docker_controller_service_running

    - name: "UnionFS | Docker | Container Stop | Gather list of running Docker containers"
      ansible.builtin.shell: "docker ps --format '{{ '{{' }} .Names{{ '}}' }}' | xargs echo -n"
      register: unionfs_docker_running_containers_ps
      ignore_errors: true

    - name: "UnionFS | Docker | Container Stop | Set 'containers_list' variable"
      ansible.builtin.set_fact:
        containers_list: "{{ unionfs_docker_running_containers_ps.stdout }}"

    - name: "UnionFS | Docker | Container Stop | Stop Saltbox Docker containers"
      ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/stop_saltbox_docker_containers.yml"
      when: (containers_list | trim | length > 0) and unionfs_docker_controller_service_running

    - name: "UnionFS | Docker | Container Stop | Stop all running Docker containers"
      ansible.builtin.shell: "docker stop {{ containers_list }}"
      ignore_errors: true
      when: (containers_list | trim | length > 0)

    - name: "UnionFS | Docker | Container Stop | Stop docker service"
      ansible.builtin.systemd_service:
        name: docker
        state: stopped

    - name: "UnionFS | Docker | Container Stop | Stop docker socket"
      ansible.builtin.systemd_service:
        name: docker.socket
        state: stopped
